# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_pricepolicy_project_projectuser_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#403137'), (2, '#314F49'), (3, '#82501E'), (4, '#A35229'), (5, '#0D4E73'), (6, '#4B7A95'), (7, '#E87A68')], default=1, verbose_name='颜色'),
        ),
    ]
