# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-17 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220215_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuestype',
            name='project',
        ),
        migrations.DeleteModel(
            name='IssuesType',
        ),
    ]
