# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_projectinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='star',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='asset',
            field=models.IntegerField(default=1000, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='star',
            field=models.SmallIntegerField(choices=[(1, '一星级'), (2, '二星级'), (3, '三星级')], default=2, verbose_name='星级'),
        ),
    ]
