# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20220220_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='star',
            field=models.BooleanField(default=False, verbose_name='星标'),
        ),
    ]
