# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_projectuser_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '任务发放者'), (2, '任务领取者')], default=2, verbose_name='用户类型'),
        ),
    ]
