# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_userinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepolicy',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='pricepolicy',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_policy',
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '一星级'), (2, '二星级'), (3, '三星级')], default=1, verbose_name='收费类型'),
        ),
    ]
