# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220220_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='star',
            field=models.SmallIntegerField(choices=[(1, '一星级'), (2, '二星级'), (3, '三星级')], default=1, verbose_name='星级'),
        ),
    ]
