# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20220220_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='count',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未领取'), (2, '已领取')], verbose_name='状态'),
        ),
    ]
