# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-20 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20220220_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='price_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.PricePolicy', verbose_name='价格策略'),
            preserve_default=False,
        ),
    ]
