# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-02-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_userinfo_price_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='price_policy',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='star',
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(default=22.0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(default=22.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='latitude',
            field=models.FloatField(default=22.0, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='longitude',
            field=models.FloatField(default=22.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='reputation',
            field=models.FloatField(default=1000, verbose_name='信誉值'),
        ),
        migrations.DeleteModel(
            name='PricePolicy',
        ),
    ]
