# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20220227_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_count',
            field=models.SmallIntegerField(default=100, verbose_name='总人数'),
        ),
    ]
