# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_project_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grow',
            field=models.IntegerField(default=20, verbose_name='任务所在地区发达程度'),
        ),
        migrations.AddField(
            model_name='project',
            name='hard',
            field=models.IntegerField(default=20, verbose_name='任务难易程度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_price',
            field=models.FloatField(verbose_name='任务佣金'),
        ),
    ]
