# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-28 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='already',
            field=models.BooleanField(default=False, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='grow',
            field=models.IntegerField(choices=[(20, '经济发展水平高'), (15, '经济发展水平较高'), (10, '经济发展水平一般'), (5, '经济发展水平不高')], default=20, verbose_name='任务所在地区发达程度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hard',
            field=models.IntegerField(choices=[(20, '困难任务'), (10, '一般困难任务'), (5, '简单任务')], default=20, verbose_name='任务难易程度'),
        ),
    ]
