# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-04-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20220428_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='task_price',
            field=models.FloatField(default=65, verbose_name='任务价格'),
        ),
    ]
